### PR TITLE
mDNS works, +/- Brightness, Readme update

### PR DESCRIPTION
**Pull request by darkpoet78**
I pushed a bunch of little updates... Well, here's a big one! I had to hack around the Brightness area a lot to get that working (it's independent of the config and temporary for now). I probably removed some stuff too because with all the hacking I did, the code itself may not know what triggered the brightness change. Lol.

The mDNS also works fully. The device should restart after changing the name due to the mDNS as well. And the Readme has a bunch of re-formatting, some big blocks split into sub-sections... Whew. I think I'm done for now. If this were for sale, I might buy it!

### CODE REVIEW

**Comment by darkpoet78** [comment]
Turns out trying to fold 12hr time into currentDisplayTime may have been messing up the alarms! ...and the first push was bad.  I missed a bracket.  So, did some re-formatting and a little better code.  Lol.  I think I'm done.

**Comment by EdenRidgway** [comment]
Nicely done on sorting out the mDNS issue.

**Comment by darkpoet78** [comment]
Thank you!  I think I'm done for now.  Lol, not my first foray into Arduino but I think the first time I did something actually useful.  I hope my hacky code (esp. the 12/24 hour stuff) works out!

**Comment by EdenRidgway** [comment]
Thank you very much for all your work. The improvements you've made really have made it much better. Much appreciated.

**Pull request merged**
