### PR TITLE
Added ArduinoOTA code & colon blink & 12 Hour Mode

### PR DESCRIPTION
**Pull request by darkpoet78**
Added Arduino OTA Code.  I lost AP data so I had to switch to its hotspot and re-enter my local Wi-fi info, I did not have to re-upload SPIFFs... although I did anyway just as a test after that.  Seems to work pretty well!

### CODE REVIEW

**Comment by darkpoet78** [comment]
Well... it worked at first but on the second try, it failed.  No hotspot, no nothing...  I'll give it another shot later but feel free to reject the merge...  Or keep it in but with a caveat.

**Comment by darkpoet78** [comment]
Not sure why the OTA failed last night, it may have been that I hadn't selected "Generic ESP8266" as the board.  I've run it a few times now and it seems to fine.  I added code to make the colon blink, too.  That was a minor feature but... anyways.

**Comment by darkpoet78** [comment]
The Readme has been edited here, too.

**Comment by MacSass** [comment]
I really like the idea of having OTA, as I want to set my clock free of the serial cables ... hope that will make it into the main branch.

**Comment by EdenRidgway** [comment]
I completely agree with the need to get the OTA updates working! Setting up the wires to flash the clock is a pain. Thanks for doing this work! Hopefully I'll find time to look at it today or tomorrow morning and get it merged in.

**Comment by EdenRidgway** [comment]
Good stuff! Thanks for making these changes. Really glad you are contributing and improving the firmware.

I would like to suggest a small tweak in terms of naming convention in the json. If we could keep the json names camel case it would help to keep it consistent. So if  
json["TwelvehourMode"] could be changed to json["twelvehourMode"] that would be great.

Thanks!

**Comment by darkpoet78** [comment]
Actually I originally did but gettwelvehourMode and settwelvehourMode made my eyes squint at those tt's.  And since I barely know what I'm doing, I made the json and variables consistent...  I think I can fix it so it's just the json...

**Comment by darkpoet78** [comment]
Lol.  Nope.  I ended up doing a find and replace all so it's consistent.  No worries.  The only disappointment I have with these cosmetic changes is that it appears the TM1650 can't display the dots while using the colon.  I was hoping to add a "PM" dot on the right side... unless there's a Matrix.something call I missed.

**Pull request merged**
